name: Build and Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Download JSON
        uses: satak/webrequest-action@master
        with:
          url: https://www.coolbet.com/s/casino-statistics/fo/game-played-count
          method: GET
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
