name: Build and Deploy

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - 'master'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy Build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ./dist
          publish_dir: ./dist
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ./dist
          publish_dir: ./dist
